### PR TITLE
Improve config file handling

### PR DESCRIPTION
**Pull request by djmitche**
Allow ~/.invtool.conf as well, and parse all three config files if they
exist, rather than only using one.  Still fail if none exist.

### CODE REVIEW

**Comment by uberj** [comment]
I like the idea of a having a another config file in the home dir of the user -- this even seems more sane that `/etc/invtoo.conf`.

Unfortunately this patch breaks some preexisting logic that was decided on when we first implemented keyring support (seehttps://github.com/uberj/inv-tool/pull/2#issuecomment-16749966). We need to be able to elect a specific config file that the user is going to use because invtool will write to it in an attempt to help configure itself.

Also, this patch needs to handle the behavior of `invtool status`, which relies on a variable `CONFIG_FILE` being present in the `invtool.lib.config` module.

**Comment by djmitche** [comment]
Hm, I thought I pushed some updates to fix that, but yes, those are problems.

As for writing the config file -- I don't see a great reason to use `./etc/invtool.conf`, but I think it makes sense to automatically write there by default.  The status should probably display _all_ of the config files parsed.  I will update the pull to handle that.

**Comment by djmitche** [comment]
Updates pushed.

**Comment by uberj** [comment]
Recapping our IRC discussion:

We should ditch `./etc/invtoo.conf` and instead use `~/.invtool.conf`.

One thing we need to account for is the case when a user hasn't installed `~/.invtool.conf` but does have `/etc/invtool.conf` installed. Should we create the file or exclusively use `/etc/invtoo.conf` when invtool tries to store the ldap username? (see https://github.com/uberj/inv-tool/pull/11/files#L1R83)

Said another way, right now _one_ config file is being chosen as the only config (https://github.com/uberj/inv-tool/blob/master/invtool/lib/config.py#L10). This is how invtool decides which one to write to. Since you are passing a list of files into `read()`, this will have to be addressed.

**Comment by djmitche** [comment]
593bc6e addresses this - it always writes to `~/.invtool.conf`.  This makes sense, since keychains are per-user, and neither per-directory (`./etc/invtool.conf`) nor per-system (`/etc/invtool.conf`).

**Comment by djmitche** [comment]
I still get this while trying to run invtool:

```
dustin@euclid ~ $ invtool search -q bld-lion-r5-089.build.mozilla.org
Traceback (most recent call last):
  File "/usr/bin/invtool-python2.7", line 3, in <module>
    from invtool.main import main
  File "/usr/lib64/python2.7/site-packages/invtool/main.py", line 20, in <module>
    __import__(d)
  File "/usr/lib64/python2.7/site-packages/invtool/dns_dispatch.py", line 6, in <module>
    from invtool.dispatch import ObjectDispatch
  File "/usr/lib64/python2.7/site-packages/invtool/dispatch.py", line 10, in <module>
    from invtool.lib.config import REMOTE, auth, API_MAJOR_VERSION
  File "/usr/lib64/python2.7/site-packages/invtool/lib/config.py", line 18, in <module>
    .format(GLOBAL_CONFIG_FILE)
Exception: Can't find global config file '/etc/invtool.conf'
dustin@euclid ~ $ which invtool
/usr/bin/invtool
dustin@euclid ~ $ ls -al .invtool.conf 
-rw-r--r-- 1 dustin dustin 152 Dec  2 11:38 .invtool.conf
```

can you merge this change and release?

**Comment by uberj** [comment]
oh! one other thing. Can you bump the version here https://github.com/uberj/inv-tool/blob/master/invtool/lib/config.py#L6 ?

**Comment by djmitche** [comment]
Yep, and I'll test it out too.

**Comment by djmitche** [comment]
OK, done and ready to go

**Pull request merged**
